spring:
  application.name: gym-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gym_app}
    username: ${DB_USER:mario}
    password: ${DB_PASS:Sql1234}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: core
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

  flyway:
    enabled: true
    schemas: core
    default-schema: core

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
